version: '3.1'
services:
  mydb:
    build: 
      context: ./database
      dockerfile: mysql.Dockerfile  
    volumes:
       - db_data:/var/lib/mysql  
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123  
    networks:
      - containernetwork  
  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - containernetwork 
  exchange1:
    build: 
      context: .
      args: 
        FOLDER: exchange
    depends_on:
      - eureka
      - mydb
    ports:
      - "8000:8000"
    networks:
      - containernetwork
    environment:
      SERVER_PORT: 8000
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: 123
      DATABASE_NAME: exchange
      DATABASE_PORT: 3306  
    # deploy:
    #   mode: replicated
    #   replicas: 6   
  transaction1:
    build: 
      context: .
      args: 
        FOLDER: transaction
    depends_on:
      - eureka
      - mydb      
    ports:
      - "8100:8100" 
    networks:
      - containernetwork  
    environment:
      SERVER_PORT: 8100
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: 123
      DATABASE_NAME: transaction
      DATABASE_PORT: 3306 
networks:
  containernetwork:
    driver: bridge
volumes:
    db_data:    