version: '3.1'
services:
  mydb:
    build: .
    volumes:
       - db_data:/var/lib/mysql  
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123  
    networks:
      - containernetwork  
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080" 
    volumes:
      - jenkins-data:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home
  db_postgres:
    image: postgres
    networks:
      - networksonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql      
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - networksonar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db_postgres:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      # - sonarqube_extensions:/opt/sonarqube/extensions
      # - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins      
networks:
  containernetwork:
    driver: bridge
  networksonar:
    driver: bridge    
volumes:
  db_data:    
  volumes:
  sonarqube_conf:
  sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins-data: