spring:
  profiles:
    active: port8001
  application:
    name: transaction
  datasource:
    url: jdbc:mysql://localhost:3306/transaction?useSSL=false
    username: root
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8001
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
