spring:
  profiles:
    active: port8002
  application:
    name: transaction
  datasource:
    jdbc: mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    #driver-class-name: com.mysql.jdbc.Driver <- teste se der ok
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
