spring:
  application:
    name: transaction
  datasource:
    #jdbc: mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:exchange}?useSSL=false
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:exchange}?useSSL=false
    #url: jdbc:mysql://localhost:3306/exchange?useSSL=false
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8000}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# spring:
#   application:
#     name: exchange
#   datasource:
#     url: jdbc:mysql://localhost:3306/exchange?useSSL=false
#     username: root
#     password: 123
#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     hibernate:
#       ddl-auto: update
# eureka:
#   client:
#     service-url:
#       default-zone: http://localhost:8761/eureka