spring:
  application:
    name: exchange
  datasource:
    url: jdbc:mysql://localhost:3306/exchange?useSSL=false
    username: root
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka