version: '3.3'

services:
   db1:
     image: mariadb:latest
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: banco
       MYSQL_USER: root
       MYSQL_PASSWORD: 123
   db2:
     image: mariadb:latest
     ports:
       - "3307:3307"
     volumes:
       - db_data:/var/lib/mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: banco
       MYSQL_USER: root
       MYSQL_PASSWORD: 123
   db3:
     image: mariadb:latest
     ports:
       - "3308:3308"
     volumes:
       - db_data:/var/lib/mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: banco
       MYSQL_USER: root
       MYSQL_PASSWORD: 123       

volumes:
    db_data: